In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine;
import warnings
warnings.filterwarnings("ignore")

In [2]:
engine = create_engine('mysql+mysqlconnector://root:ankit9548694709@localhost:3306/bfsi')

df = pd.read_sql('SELECT * FROM cleaned_loan_data', con=engine)

In [3]:
df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,...,REGION_RATING_CLIENT,REGION_POPULATION_RELATIVE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,CODE_GENDER,AGE_YEARS,YEARS_EMPLOYED,OCCUPATION_TYPE,INCOME_TO_CREDIT_RATIO
0,100002,1,Cash loans,0,202500.0,406597.5,24700.5,Working,Secondary / secondary special,Single / not married,...,2,0.018801,0.083037,0.262949,0.139376,M,25.0,1.0,Laborers,0.4980
1,100003,0,Cash loans,0,270000.0,1293502.5,35698.5,State servant,Higher education,Married,...,1,0.003541,0.311267,0.622246,NaN,F,45.0,3.0,Core staff,0.2087
2,100004,0,Revolving loans,0,67500.0,135000.0,6750.0,Working,Secondary / secondary special,Single / not married,...,2,0.010032,NaN,0.555912,0.729567,M,52.0,0.0,Laborers,0.5000
3,100006,0,Cash loans,0,135000.0,312682.5,29686.5,Working,Secondary / secondary special,Civil marriage,...,2,0.008019,NaN,0.650442,NaN,F,52.0,8.0,Laborers,0.4317
4,100007,0,Cash loans,0,121500.0,513000.0,21865.5,Working,Secondary / secondary special,Single / not married,...,2,0.028663,NaN,0.322738,NaN,M,54.0,8.0,Core staff,0.2368

In [4]:
df.shape

(307511, 21)

In [5]:
df.columns

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CNT_CHILDREN',
       'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'NAME_INCOME_TYPE',
       'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE',
       'REGION_RATING_CLIENT', 'REGION_POPULATION_RELATIVE', 'EXT_SOURCE_1',
       'EXT_SOURCE_2', 'EXT_SOURCE_3', 'CODE_GENDER', 'AGE_YEARS',
       'YEARS_EMPLOYED', 'OCCUPATION_TYPE', 'INCOME_TO_CREDIT_RATIO'],
      dtype='str')

In [6]:
df.isnull().sum()

SK_ID_CURR                         0
TARGET                             0
NAME_CONTRACT_TYPE                 0
CNT_CHILDREN                       0
AMT_INCOME_TOTAL                   0
AMT_CREDIT                         0
AMT_ANNUITY                       12
NAME_INCOME_TYPE                   0
NAME_EDUCATION_TYPE                0
NAME_FAMILY_STATUS                 0
NAME_HOUSING_TYPE                  0
REGION_RATING_CLIENT               0
REGION_POPULATION_RELATIVE         0
EXT_SOURCE_1                  173378
EXT_SOURCE_2                     660
EXT_SOURCE_3                   60965
CODE_GENDER                        0
AGE_YEARS                          0
YEARS_EMPLOYED                 55374
OCCUPATION_TYPE                    0
INCOME_TO_CREDIT_RATIO             0
dtype: int64

In [7]:
# Exploratory Data Analysis (EDA) — Default Rate Across Different Applicant Segments

In [8]:
df[df['YEARS_EMPLOYED'].isnull()]['NAME_INCOME_TYPE'].value_counts()

NAME_INCOME_TYPE
Pensioner     55352
Unemployed       22
Name: count, dtype: int64

In [9]:
df.describe()

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,REGION_RATING_CLIENT,REGION_POPULATION_RELATIVE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,AGE_YEARS,YEARS_EMPLOYED,INCOME_TO_CREDIT_RATIO
count,307511.000000,307511.000000,307511.000000,3.075110e+05,3.075110e+05,307499.000000,307511.000000,307511.000000,134133.000000,3.068510e+05,246546.000000,307511.000000,252137.000000,307511.000000
mean,278180.518577,0.080729,0.417052,1.687979e+05,5.990260e+05,27108.573909,2.052463,0.020868,0.502130,5.143927e-01,0.510853,43.435968,6.037008,0.399670
std,102790.175348,0.272419,0.722121,2.371231e+05,4.024908e+05,14493.737315,0.509034,0.013831,0.211062,1.910602e-01,0.194844,11.954593,6.416079,0.507924
min,100002.000000,0.000000,0.000000,2.565000e+04,4.500000e+04,1615.500000,1.000000,0.000290,0.014568,8.173617e-08,0.000527,20.000000,0.000000,0.011800
25%,189145.500000,0.000000,0.000000,1.125000e+05,2.700000e+05,16524.000000,2.000000,0.010006,0.334007,3.924574e-01,0.370650,34.000000,2.000000,0.193800
50%,278202.000000,0.000000,0.000000,1.471500e+05,5.135310e+05,24903.000000,2.000000,0.018850,0.505998,5.659614e-01,0.535276,43.000000,4.000000,0.306300
75%,367142.500000,0.000000,1.000000,2.025000e+05,8.086500e+05,34596.000000,2.000000,0.028663,0.675053,6.636171e-01,0.669057,53.000000,8.000000,0.495400
max,456255.000000,1.000000,19.000000,1.170000e+08,4.050000e+06,258025.500000,3.000000,0.072508,0.962693,8.549997e-01,0.896010,69.000000,49.000000,208.003300

In [10]:
# Q1: Default Rate Analysis by Loan Contract Type

In [11]:
df.groupby('NAME_CONTRACT_TYPE')['TARGET'].mean()*100

NAME_CONTRACT_TYPE
Cash loans         8.345913
Revolving loans    5.478329
Name: TARGET, dtype: float64

In [12]:
# Q2: Default Rate Analysis by Education Type

In [13]:
df.groupby('NAME_EDUCATION_TYPE')['TARGET'].mean() * 100

NAME_EDUCATION_TYPE
Academic degree                   1.829268
Higher education                  5.355115
Incomplete higher                 8.484966
Lower secondary                  10.927673
Secondary / secondary special     8.939929
Name: TARGET, dtype: float64

In [14]:
# Q2: Default Rate Analysis by Occupation Type

In [15]:
df.groupby('OCCUPATION_TYPE')['TARGET'].mean()*100

OCCUPATION_TYPE
Accountants               4.830327
Cleaning staff            9.606705
Cooking staff            10.443996
Core staff                6.303954
Drivers                  11.326130
HR staff                  6.394316
High skill tech staff     6.159930
IT staff                  6.463878
Laborers                 10.578770
Low-skill Laborers       17.152413
Managers                  6.214028
Medicine staff            6.700246
Private service staff     6.598793
Realty agents             7.856192
Sales staff               9.631799
Secretaries               7.049808
Security staff           10.742449
Unknown                   6.513056
Waiters/barmen staff     11.275964
Name: TARGET, dtype: float64

In [16]:
# Q3: Default Rate Analysis by Age Group

In [17]:
df["AGE_GROUP"]=pd.cut(df['AGE_YEARS'],bins=[20,30,40,50,60,70],labels=['20-30','30-40','40-50','50-60','60-70'])

In [18]:
df.groupby('AGE_GROUP')['TARGET'].mean() * 100

AGE_GROUP
20-30    11.398542
30-40     9.286909
40-50     7.550974
50-60     5.933440
60-70     4.920321
Name: TARGET, dtype: float64

In [19]:
# Q3: Default Rate Analysis by Region Rating

In [20]:
df.groupby('REGION_RATING_CLIENT')['TARGET'].mean()*100

REGION_RATING_CLIENT
1     4.820325
2     7.889102
3    11.102835
Name: TARGET, dtype: float64

In [21]:
# Q3: Default Rate Analysis by Gender

In [22]:
df.groupby('CODE_GENDER')['TARGET'].mean() * 100

CODE_GENDER
F           6.999328
M          10.141920
Unknown     0.000000
Name: TARGET, dtype: float64

In [23]:
# Q4: Default Rate Analysis by Credit Amount Group

In [24]:
df["CREDIT_GROUP"]=pd.qcut(df["AMT_CREDIT"],q=4,labels=['Low','Medium','High','Very High'])
df.groupby('CREDIT_GROUP')['TARGET'].mean() * 100

CREDIT_GROUP
Low          7.242958
Medium       9.683407
High         9.161032
Very High    6.214086
Name: TARGET, dtype: float64

In [25]:
# Q4: Default Rate Analysis by Income-to-Credit Ratio Group

In [26]:
df['RATIO_GROUP'] = pd.qcut(df['INCOME_TO_CREDIT_RATIO'], q=4, labels=['Low','Medium','High','Very High'])
df.groupby('RATIO_GROUP')['TARGET'].mean() * 100

RATIO_GROUP
Low          7.367340
Medium       8.742259
High         8.737334
Very High    7.443066
Name: TARGET, dtype: float64

In [27]:
# Q4: Correlation Analysis of External Credit Scores (EXT_SOURCE) with Default

In [28]:
df.groupby('RATIO_GROUP')['TARGET'].agg(['count', 'sum', 'mean'])

             count   sum      mean
RATIO_GROUP
Low          76907  5666  0.073673
Medium       76868  6720  0.087423
High         76980  6726  0.087373
Very High    76756  5713  0.074431

In [29]:
# Risk Score Logic: Rule-Based High Risk Classification

In [30]:
df[['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'TARGET']].corr()

              EXT_SOURCE_1  EXT_SOURCE_2  EXT_SOURCE_3    TARGET
EXT_SOURCE_1      1.000000      0.213982      0.186846 -0.155317
EXT_SOURCE_2      0.213982      1.000000      0.109167 -0.160472
EXT_SOURCE_3      0.186846      0.109167      1.000000 -0.178919
TARGET           -0.155317     -0.160472     -0.178919  1.000000

In [31]:
def risk_score(row):
    if row['EXT_SOURCE_3'] < 0.3 and row['AGE_YEARS'] < 30 and row['REGION_RATING_CLIENT'] == 3:
                return 'High Risk'
    else:
        return 'Low Risk'
        
df['RISK_CATEGORY'] = df.apply(risk_score, axis=1)

In [32]:
df['RISK_CATEGORY'].value_counts()

RISK_CATEGORY
Low Risk     306007
High Risk      1504
Name: count, dtype: int64

In [33]:
df.groupby('RISK_CATEGORY')['TARGET'].mean() * 100

RISK_CATEGORY
High Risk    23.803191
Low Risk      7.995569
Name: TARGET, dtype: float64

In [34]:
df.to_csv("Final_Loan_Data.csv",index=False)

In [36]:
df.to_csv('final_loan_data.csv', index=False)

In [38]:
print(df.columns.tolist())

['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'REGION_RATING_CLIENT', 'REGION_POPULATION_RELATIVE', 'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'CODE_GENDER', 'AGE_YEARS', 'YEARS_EMPLOYED', 'OCCUPATION_TYPE', 'INCOME_TO_CREDIT_RATIO', 'AGE_GROUP', 'CREDIT_GROUP', 'RATIO_GROUP', 'RISK_CATEGORY']